# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.ebrugulec.com/
basurl: /
title: Ebru Gulec
author: Ebru Gulec
description: Ebru Gulec Personl Blog
avatar: ebru.png
email: glcebru94@gmail.com
github: ebrugulec
twitter: glcebru
google_analytics: UA-47728743-1
