# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ebrugulec-com
google_analytics:
title: Ebru Güleç
url: "http://ebrugulec.com"
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ebru Güleç

description: Ebru Gulec Personal Blog
author:
  name: Ebru Gulec
  avatar: "ebru.png"
  email: ebru@ebrugulec.com
  github: ebrugulec
  twitter: glcebru
  pinterest:
  linkedin:
  bio: Computer Engineering Student
  email_md5:

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
  - jemoji
